export type NeuesWerkLocale = 'de' | 'en'

export const neuesWerkCopy = {
  de: {
    kicker: 'Geführte Eingabe',
    title: 'Neues Werk',
    sessionOne: 'Werk in dieser Sitzung',
    sessionMany: 'Werke in dieser Sitzung',
    photoFirst: 'Zuerst ein Foto.',
    photoHeading: 'Foto & Künstler:in',
    dropIdle: 'Foto hierher ziehen, auswählen — oder Kamera öffnen',
    dropUploading: 'Wird hochgeladen…',
    previewAlt: 'Vorschau',
    contextPreviewAlt: 'Kontextfoto-Vorschau',
    contextPhoto: 'Kontextfoto (optional)',
    contextDrop: 'Kontextfoto hierher ziehen, auswählen — oder Kamera öffnen',
    contextSaved: 'Kontextfoto gespeichert',
    contextReplace: 'Tippen zum Ersetzen — oder Kamera öffnen',
    aiHeading: 'Alles auf einmal',
    aiCopy: 'Prompt kopieren',
    aiCopied: 'Kopiert',
    aiPaste: 'Antwort einfügen',
    aiApply: 'Übernehmen',
    aiMalformed: 'Die Antwort ließ sich nicht lesen. Bitte nur das JSON einfügen.',
    aiExplanation:
      'Prompt kopieren, Foto anhängen, Antwort hier einfügen. Gesehenes aus dem Foto wird direkt übernommen (✦). Recherche braucht Quellen — bitte Links prüfen.',
    promptBadgeResearch: (name: string) => `Mit Recherche zu ${name}`,
    promptBadgePhotoOnly: 'Nur Bildbeschreibung',
    signatureNote: (s: string) => `Im Bild lesbar: „${s}" — Künstler:in prüfen.`,
    nameSuggestion: (name: string) => `Vorschlag: ${name}`,
    nameSuggestionAccept: 'Übernehmen',
    nameSuggestionDismiss: 'Verwerfen',
    nameSuggestionOpenSource: 'Quelle prüfen',
    workHeading: 'Das Werk',
    whereHeading: 'Wo',
    rightsHeading: 'Rechte',
    altDe: 'Alt-Text DE (Pflicht)',
    altEn: 'Alt-Text EN (optional)',
    workTitle: 'Titel',
    year: 'Jahr',
    medium: 'Technik',
    mediumDe: 'Technik DE',
    mediumEn: 'Technik EN',
    mediumHelp: 'Leer lassen, wenn die Technik noch unklar ist.',
    artform: 'Kunstform',
    surface: 'Untergrund',
    surfaceDe: 'Untergrund DE',
    surfaceEn: 'Untergrund EN',
    surfacePlaceholder: 'Putz, Beton, Holz…',
    subjects: 'Motive (Tags)',
    subjectsHelp: 'Aus dem Vokabular oder als neuer Vorschlag.',
    subjectsNewNote: 'Neu — wird dem Vokabular hinzugefügt',
    size: 'Größe',
    story: 'Geschichte (DE)',
    storyHelp: 'Ohne Geschichte schließt sich die Seite unter dem Locator.',
    exhibition: 'Teil einer Ausstellung?',
    artist: 'Künstler:in',
    artistPlaceholder: 'Name oder Alias',
    createArtist: (name: string) => `„${name}" neu anlegen`,
    carried: 'Übernommen aus dem letzten Werk — ein Klick genügt zum Ändern.',
    floor: 'Ort im Haus',
    spot: 'Ort',
    spotPlaceholder: 'bei den Aufzügen',
    spotHelp: 'Wo genau? So, dass ein Gast es findet.',
    spotHelpOutside: 'Wo genau? „Fassade zur Straße", „beim Parkplatz", „Hof, linke Wand".',
    permission: 'Foto-Freigabe',
    permissionNote: 'Notiz zur Freigabe',
    creditText: 'Foto-Credit / Bildnachweis',
    missingPrefix: 'Fehlt noch:',
    canPublish: 'Kann veröffentlicht werden',
    saveNext: 'Speichern & nächstes',
    savePublish: 'Veröffentlichen',
    needPhoto: 'Bitte zuerst ein Foto hochladen.',
    needAltDe: 'Alt-Text (DE) ist Pflicht.',
    altPlaceholder: 'Alt-Text folgt',
    imageTooSmall: (got: number, need: number) =>
      `Foto zu klein: lange Seite ${got} px, mindestens ${need} px nötig (Hero-Größe).`,
    incomplete: 'Noch nicht vollständig:',
    uploadFailed: 'Upload fehlgeschlagen',
    fileTooLarge: (mb: number) =>
      `Datei nach Verkleinern noch zu groß (max. ${mb} MB). Bitte ein kleineres Foto wählen.`,
    saveFailed: 'Speichern fehlgeschlagen',
    noSource: 'ohne Quelle',
    optional: 'optional',
    identityAccept: 'Übernehmen',
    exifOffer: (lat: string, lng: string) =>
      `Im Foto steckt ein Standort: ${lat} · ${lng} — übernehmen?`,
    exifAccept: 'Übernehmen',
    exifDismiss: 'Nicht jetzt',
    captureNow: 'Standort jetzt erfassen',
    captureTooInaccurate: 'Zu ungenau — noch einmal versuchen oder auf der Karte setzen.',
    captureDenied: 'Standort nicht verfügbar.',
    mapHint: 'Pin setzen oder ziehen — Karte ums Hotel.',
    clearGeo: 'Löschen',
    suggestedMark: '✦',
    floorLabel: (value: string) => {
      if (value === 'outside') return 'Außen'
      if (value === 'basement') return 'Keller'
      if (value === 'lobby') return 'Lobby'
      return `${value}. Etage`
    },
  },
  en: {
    kicker: 'Guided entry',
    title: 'New work',
    sessionOne: 'work in this session',
    sessionMany: 'works in this session',
    photoFirst: 'A photo first.',
    photoHeading: 'Photo & artist',
    dropIdle: 'Drop a photo here, pick one — or open the camera',
    dropUploading: 'Uploading…',
    previewAlt: 'Preview',
    contextPreviewAlt: 'Context photo preview',
    contextPhoto: 'Context photo (optional)',
    contextDrop: 'Drop a context photo here, pick one — or open the camera',
    contextSaved: 'Context photo saved',
    contextReplace: 'Tap to replace — or open the camera',
    aiHeading: 'All at once',
    aiCopy: 'Copy prompt',
    aiCopied: 'Copied',
    aiPaste: 'Paste the answer',
    aiApply: 'Apply',
    aiMalformed: 'Could not read that reply. Paste the JSON only.',
    aiExplanation:
      'Copy the prompt, attach the photo, paste the answer here. Photo-seen values fill in (✦). Research needs sources — please check the links.',
    promptBadgeResearch: (name: string) => `With research on ${name}`,
    promptBadgePhotoOnly: 'Photo description only',
    signatureNote: (s: string) => `Readable in the image: “${s}” — check the artist.`,
    nameSuggestion: (name: string) => `Suggestion: ${name}`,
    nameSuggestionAccept: 'Use it',
    nameSuggestionDismiss: 'Dismiss',
    nameSuggestionOpenSource: 'Check source',
    workHeading: 'The work',
    whereHeading: 'Where',
    rightsHeading: 'Rights',
    altDe: 'Alt text DE (required)',
    altEn: 'Alt text EN (optional)',
    workTitle: 'Title',
    year: 'Year',
    medium: 'Technique',
    mediumDe: 'Technique DE',
    mediumEn: 'Technique EN',
    mediumHelp: 'Leave blank if the technique is still unclear.',
    artform: 'Art form',
    surface: 'Surface',
    surfaceDe: 'Surface DE',
    surfaceEn: 'Surface EN',
    surfacePlaceholder: 'Plaster, concrete, wood…',
    subjects: 'Subjects (tags)',
    subjectsHelp: 'From the vocabulary, or as a new proposal.',
    subjectsNewNote: 'New — will be added to the vocabulary',
    size: 'Size',
    story: 'Story (DE)',
    storyHelp: 'Without a story the page closes under the locator.',
    exhibition: 'Part of an exhibition?',
    artist: 'Artist',
    artistPlaceholder: 'Name or alias',
    createArtist: (name: string) => `Create “${name}”`,
    carried: 'Carried over from the last work — one click to change.',
    floor: 'Place in the building',
    spot: 'Spot',
    spotPlaceholder: 'near the lifts',
    spotHelp: 'Where exactly? So a guest can find it.',
    spotHelpOutside:
      'Where exactly? “street façade”, “by the car park”, “courtyard, left wall”.',
    permission: 'Photo permission',
    permissionNote: 'Permission note',
    creditText: 'Photo credit',
    missingPrefix: 'Still missing:',
    canPublish: 'Ready to publish',
    saveNext: 'Save & next',
    savePublish: 'Publish',
    needPhoto: 'Upload a photo first.',
    needAltDe: 'Alt text (DE) is required.',
    altPlaceholder: 'Alt text pending',
    imageTooSmall: (got: number, need: number) =>
      `Photo too small: long edge ${got} px, need at least ${need} px (hero size).`,
    incomplete: 'Not complete yet:',
    uploadFailed: 'Upload failed',
    fileTooLarge: (mb: number) =>
      `File is still too large after compression (max ${mb} MB). Please choose a smaller photo.`,
    saveFailed: 'Save failed',
    noSource: 'no source',
    optional: 'optional',
    identityAccept: 'Apply checked',
    exifOffer: (lat: string, lng: string) =>
      `This photo has a location: ${lat} · ${lng} — use it?`,
    exifAccept: 'Use it',
    exifDismiss: 'Not now',
    captureNow: 'Capture location now',
    captureTooInaccurate: 'Too inaccurate — try again or set it on the map.',
    captureDenied: 'Location unavailable.',
    mapHint: 'Drop or drag the pin — map centred on the hotel.',
    clearGeo: 'Clear',
    suggestedMark: '✦',
    floorLabel: (value: string) => {
      if (value === 'outside') return 'Outside'
      if (value === 'basement') return 'Basement'
      if (value === 'lobby') return 'Lobby'
      return `Floor ${value}`
    },
  },
} as const

/** Admin UI language from Payload's language switcher (not content locale). */
export function neuesWerkLocale(code: string | undefined): NeuesWerkLocale {
  return code?.toLowerCase().startsWith('en') ? 'en' : 'de'
}
