import amenityTagsSeed from './data/amenity-tags.json'

import type { AmenityTagSeed } from './types'

export const tagsSeed = [
  { name: 'Art', slug: 'art', type: 'category' as const },
  { name: 'Sport', slug: 'sport', type: 'category' as const },
  { name: 'Music', slug: 'music', type: 'category' as const },
  { name: 'Food & Drink', slug: 'food-drink', type: 'category' as const },
  { name: 'Community', slug: 'community', type: 'category' as const },
  { name: 'Neighbourhood', slug: 'neighbourhood', type: 'category' as const },
  { name: 'Culture', slug: 'culture', type: 'category' as const },
  { name: 'Screen Print', slug: 'screen-print', type: 'medium' as const },
  { name: 'Mural', slug: 'mural', type: 'medium' as const },
  { name: 'Photography', slug: 'photography', type: 'medium' as const },
  { name: 'Skateboarding', slug: 'skateboarding', type: 'theme' as const },
  { name: 'Urban Art', slug: 'urban-art', type: 'theme' as const },
  { name: 'Tiergarten', slug: 'tiergarten', type: 'neighbourhood' as const },
  { name: 'Schöneberg', slug: 'schoeneberg', type: 'neighbourhood' as const },
  ...(amenityTagsSeed as AmenityTagSeed[]),
]

export const hotelSeed = {
  name: 'Hotel Berlin, Berlin',
  legalName: 'Pandox Berlin GmbH',
  url: 'https://hotel-berlin.de',
  telephone: '+493026050',
  conferencePhone: '+4930260526 02',
  email: 'info@hotel-berlin.de',
  address: {
    streetAddress: 'Lützowplatz 17',
    addressLocality: 'Berlin',
    postalCode: '10785',
    addressCountry: 'DE',
  },
  geo: { latitude: 52.5036, longitude: 13.3522 },
  hasMap: 'https://maps.google.com/?q=52.5036,13.3522',
  directionsUrl:
    'https://www.google.com/maps/dir/?api=1&destination=52.5036,13.3522',
  mapBounds: {
    north: 52.516,
    south: 52.497,
    west: 13.34,
    east: 13.378,
  },
  checkinTime: '15:00',
  checkoutTime: '12:00',
  starRating: 4,
  priceRange: '€€',
  totalRooms: 701,
  foundingDate: '1958',
  brand: 'Radisson Individuals',
  parentOrganization: 'Pandox AB',
  wikidataId: 'Q1630833',
  sameAs: [
    { url: 'https://www.facebook.com/hotel.berlin/' },
    { url: 'https://www.instagram.com/hotel_berlin_berlin/' },
    { url: 'https://www.wikidata.org/entity/Q1630833' },
  ],
  amenityFeature: [
    { name: 'Free WiFi', value: true },
    { name: 'Underground Parking', value: true },
    { name: 'Sauna', value: true },
    { name: 'Fitness Centre', value: true },
    { name: 'Pet Friendly', value: true },
    { name: 'EV Charging Nearby', value: true },
    { name: '24/7 Reception', value: true },
    { name: 'Luggage Storage', value: true },
    { name: 'Non-Smoking Rooms', value: true },
    { name: 'Accessible Rooms Available', value: true },
  ],
  certifications: [
    { name: 'BREEAM', url: 'https://breaam.com' },
    { name: 'The Green Key', url: 'https://www.green-key.org' },
    { name: 'Cvent Top 25 Europe Independent Hotels' },
    { name: 'Sustainable Meetings Berlin Leader' },
    { name: 'Sustainable Berlin Leader' },
  ],
  openingHours: {
    reception: 'Mo-Su 00:00-24:00',
    breakfast: 'Mo-Su 06:30-10:00',
  },
  hours: [
    { dayOfWeek: 'Mo-Su', opens: '00:00', closes: '24:00', segment: 'Reception' },
    { dayOfWeek: 'Mo-Fr', opens: '06:30', closes: '10:00', segment: 'Breakfast' },
    { dayOfWeek: 'Sa-Su', opens: '06:30', closes: '11:00', segment: 'Breakfast' },
  ],
  breakfastPricing: {
    adultPrice: 23,
    childPrice: 12,
    childAgeFrom: 6,
  },
  roomService: {
    offered: false,
  },
  guestStay: {
    wifiNetwork: 'HBB_Guest',
    wifiPassword: 'welcome1958',
    checkout: {
      valueDE: '12:00',
      valueEN: '12:00',
      noteDE: 'Später auf Anfrage',
      noteEN: 'Later on request',
    },
    breakfast: {
      valueDE: '06:30 – 10:00 · Sa/So bis 11:00',
      valueEN: '06:30 – 10:00 · Sat/Sun until 11:00',
      noteDE: 'Lütze, Erdgeschoss',
      noteEN: 'Lütze, ground floor',
    },
    parking: {
      valueDE: '4 € / Std.',
      valueEN: '€4 / hour',
      noteDE: 'Tiefgarage · max. 25 €/Tag',
      noteEN: 'Underground · max. €25/day',
    },
    luggage: {
      valueDE: 'Rezeption',
      valueEN: 'Reception',
      noteDE: 'Auch nach dem Check-out',
      noteEN: 'Also after check-out',
    },
    more: {
      saunaFitness: {
        valueDE: '24/7',
        valueEN: '24/7',
        noteDE: 'Sauna · Fitness',
        noteEN: 'Sauna · gym',
      },
      pets: {
        valueDE: '€30 / Tag',
        valueEN: '€30 / day',
        noteDE: 'Hunde willkommen',
        noteEN: 'Dogs welcome',
      },
    },
  },
  bridgeNav: {
    toHereLabelEN: 'Already in the house? ENTER →',
    toHereLabelDE: 'Schon im Haus? ENTER →',
    toStayLabelEN: 'Not here yet? STAY →',
    toStayLabelDE: 'Noch nicht hier? BLEIB →',
  },
}

export const meetingRoomsSeed = [
  {
    name: { en: 'Berlin, Berlin', de: 'Berlin, Berlin' },
    slug: 'berlin-berlin',
    floorSizeM2: 540,
    area: 'saal' as const,
    shortDescription: {
      en: "Big business or meetings that go on for days? We've got 540 m² so you can organize your event in big style.",
      de: 'Big Business oder tagelange Konferenzen? Auf 540 m² bringen wir Ihr Event im Tagungsraum Berlin, Berlin ganz groß raus.',
    },
    description: {
      en: "Big business or meetings that go on for days? We've got 540 m² so that you can organize your event in big style! Whether you're into theater or want a flashy reception, our team will help you get it just right!",
      de: 'Big Business oder tagelange Konferenzen? Wir geben alles: auf 540 m² bringen wir Ihr Event im Tagungsraum Berlin, Berlin ganz groß raus. Machen Sie also ruhig großes Theater oder Tamtam beim Empfang, unser Team hält Ihnen organisatorisch den Rücken frei.',
    },
    capacity: { classroom: 440, theater: 550, banquet: 450, cabaret: 250, reception: 1200 },
    hasScreen: true,
    hasProjector: true,
    isDivisible: true,
    hasDaylight: false,
    displayOrder: 1,
    featured: true,
  },
  {
    name: { en: 'Berlin 1', de: 'Berlin 1' },
    slug: 'berlin-1',
    floorSizeM2: 90,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 60,
      theater: 90,
      banquet: 50,
      uShape: 32,
      cabaret: 45,
      reception: 180,
      block: 35,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 2,
    featured: false,
    combinableWith: ['berlin-2', 'berlin-3'],
  },
  {
    name: { en: 'Berlin 2', de: 'Berlin 2' },
    slug: 'berlin-2',
    floorSizeM2: 90,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 60,
      theater: 90,
      banquet: 50,
      uShape: 32,
      cabaret: 45,
      reception: 260,
      block: 35,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 3,
    featured: false,
    combinableWith: ['berlin-1', 'berlin-3'],
  },
  {
    name: { en: 'Berlin 3', de: 'Berlin 3' },
    slug: 'berlin-3',
    floorSizeM2: 180,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 120,
      theater: 180,
      banquet: 150,
      uShape: 70,
      cabaret: 70,
      reception: 260,
      block: 48,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 4,
    featured: true,
    combinableWith: ['berlin-1', 'berlin-2'],
  },
  {
    name: { en: 'Berlin 4', de: 'Berlin 4' },
    slug: 'berlin-4',
    floorSizeM2: 60,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 30,
      theater: 60,
      banquet: 30,
      uShape: 25,
      cabaret: 27,
      reception: 80,
      block: 25,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 5,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-5', 'berlin-6'],
  },
  {
    name: { en: 'Berlin 5', de: 'Berlin 5' },
    slug: 'berlin-5',
    floorSizeM2: 60,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 30,
      theater: 60,
      banquet: 30,
      uShape: 25,
      cabaret: 27,
      reception: 80,
      block: 25,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 6,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-6'],
  },
  {
    name: { en: 'Berlin 6', de: 'Berlin 6' },
    slug: 'berlin-6',
    floorSizeM2: 60,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    description: {
      en: 'Big business, small business or conferences all day long? We adapt ourselves and our rooms to your needs.',
      de: 'Big Business, small business oder tagelange Konferenzen? Wir passen uns und unsere Räumen Ihren Bedürfnissen an.',
    },
    capacity: {
      classroom: 30,
      theater: 60,
      banquet: 30,
      uShape: 25,
      cabaret: 27,
      reception: 80,
      block: 25,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 7,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-5'],
  },
  {
    name: { en: 'Meeting Room A1', de: 'Tagungsraum A1' },
    slug: 'meeting-room-a1',
    floorSizeM2: 73,
    area: 'bereich-a' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A1 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A1 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A1 meeting room. A1 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A1. Der Veranstaltungsraum A1 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 40,
      theater: 60,
      banquet: 50,
      uShape: 30,
      cabaret: 45,
      reception: 90,
      block: 28,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: true,
    displayOrder: 8,
    featured: true,
  },
  {
    name: { en: 'Meeting Room A2', de: 'Tagungsraum A2' },
    slug: 'meeting-room-a2',
    floorSizeM2: 46,
    area: 'bereich-a' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A2 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A2 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A2 meeting room. A2 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A2. Der Veranstaltungsraum A2 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: { classroom: 20, theater: 30, banquet: 20, uShape: 18, reception: 40 },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: true,
    displayOrder: 9,
    featured: false,
  },
  {
    name: { en: 'Meeting Room A3', de: 'Tagungsraum A3' },
    slug: 'meeting-room-a3',
    floorSizeM2: 50,
    area: 'bereich-a' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A3 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A3 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A3 meeting room. A3 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A3. Der Veranstaltungsraum A3 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: { classroom: 24, theater: 32, banquet: 30, uShape: 20, reception: 40 },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: true,
    displayOrder: 10,
    featured: false,
  },
  {
    name: { en: 'Meeting Room A4', de: 'Tagungsraum A4' },
    slug: 'meeting-room-a4',
    floorSizeM2: 72,
    area: 'bereich-a' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A4 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A4 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our A4 meeting room. A4 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum A4. Der Veranstaltungsraum A4 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 40,
      theater: 60,
      banquet: 50,
      uShape: 30,
      cabaret: 45,
      reception: 80,
      block: 28,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: true,
    displayOrder: 11,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B1', de: 'Tagungsraum B1' },
    slug: 'meeting-room-b1',
    floorSizeM2: 30,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B1 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B1 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B1 meeting room. B1 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B1. Der Veranstaltungsraum B1 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: { reception: 8, block: 8 },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 12,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B2', de: 'Tagungsraum B2' },
    slug: 'meeting-room-b2',
    floorSizeM2: 30,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B2 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B2 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B2 meeting room. B2 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B2. Der Veranstaltungsraum B2 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: { block: 8 },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 13,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B3', de: 'Tagungsraum B3' },
    slug: 'meeting-room-b3',
    floorSizeM2: 33,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B3 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B3 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B3 meeting room. B3 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B3. Der Veranstaltungsraum B3 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 12,
      theater: 20,
      banquet: 10,
      uShape: 14,
      cabaret: 8,
      reception: 12,
      block: 12,
    },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 14,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B4', de: 'Tagungsraum B4' },
    slug: 'meeting-room-b4',
    floorSizeM2: 49,
    area: 'bereich-b' as const,
    shortDescription: {
      en: '"Black is beautiful" — enjoy state-of-the-art technology and appealing design in our B4 meeting room.',
      de: '"Black is beautiful" — genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B4.',
    },
    description: {
      en: '"Black is beautiful" — Enjoy state-of-the-art technology and appealing design in our B4 meeting room. B4 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: '"Black is beautiful" — Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B4. Der Veranstaltungsraum B4 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: { block: 20 },
    hasScreen: false,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 15,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B5', de: 'Tagungsraum B5' },
    slug: 'meeting-room-b5',
    floorSizeM2: 225,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B5 meeting room — ideal for bigger events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B5 — ideal für Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B5 meeting room. B5 is the ideal venue for bigger events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, portable touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B5. Der Veranstaltungsraum B5 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 80,
      theater: 120,
      banquet: 100,
      uShape: 35,
      cabaret: 50,
      reception: 250,
      block: 40,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 16,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B6', de: 'Tagungsraum B6' },
    slug: 'meeting-room-b6',
    floorSizeM2: 31,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B6 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B6 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B6 meeting room. B6 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B6. Der Veranstaltungsraum B6 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 12,
      theater: 20,
      banquet: 10,
      uShape: 14,
      cabaret: 8,
      reception: 12,
    },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 17,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B7', de: 'Tagungsraum B7' },
    slug: 'meeting-room-b7',
    floorSizeM2: 28,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B7 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B7 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B7 meeting room. B7 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B7. Der Veranstaltungsraum B7 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 12,
      theater: 25,
      banquet: 16,
      uShape: 14,
      block: 10,
    },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 18,
    featured: false,
  },
  {
    name: { en: 'Meeting Room B8', de: 'Tagungsraum B8' },
    slug: 'meeting-room-b8',
    floorSizeM2: 27,
    area: 'bereich-b' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B8 meeting room — ideal for smaller events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B8 — ideal für kleinere Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our B8 meeting room. B8 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum B8. Der Veranstaltungsraum B8 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 12,
      theater: 25,
      banquet: 16,
      uShape: 14,
      block: 10,
    },
    hasScreen: true,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 19,
    featured: false,
  },
  {
    name: { en: 'Meeting Room C4', de: 'Tagungsraum C4' },
    slug: 'meeting-room-c4',
    floorSizeM2: 157,
    area: 'bereich-c' as const,
    shortDescription: {
      en: 'Enjoy state-of-the-art technology and appealing design in our C4 meeting room — ideal for events, meetings, and workshops.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum C4 — ideal für Events, Meetings und Workshops.',
    },
    description: {
      en: 'Enjoy state-of-the-art technology and appealing design in our C4 meeting room. C4 is the ideal venue for smaller events, business meetings, creative brainstorming or workshops and offers an inspiring space and unparalleled service for your meetings and events. Live the spirit of innovation and create your future with us.\n\nThe room is fully equipped with latest technology such as advanced audio-visual capabilities, portable touchscreens, Click&Share and high speed internet connectivity. Our experienced staff is at hand to respond to every need.',
      de: 'Genießen Sie modernste Technik und ansprechendes Design in unserem Tagungsraum C4. Der Veranstaltungsraum C4 ist der ideale Veranstaltungsort für kleinere Events, Geschäftstreffen, kreative Brainstormings oder Workshops und bietet einen inspirierenden Raum und unvergleichlichen Service für Ihre Meetings und Veranstaltungen. Leben Sie den Geist der Innovation und gestalten Sie Ihre Zukunft mit uns.\n\nDer Raum ist mit modernster Technik ausgestattet, wie z.B. fortschrittlichen audiovisuellen Möglichkeiten, portablen Touchscreens, Click&Share und High-Speed-Internetanschlüssen. Unser erfahrenes Personal steht bereit, um auf all Ihre Bedürfnisse einzugehen.',
    },
    capacity: {
      classroom: 48,
      theater: 110,
      banquet: 100,
      uShape: 30,
      cabaret: 50,
      reception: 150,
      block: 32,
    },
    hasScreen: true,
    hasProjector: true,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 20,
    featured: false,
  },
  {
    name: { en: 'Meeting Island', de: 'Meeting Island' },
    slug: 'meeting-island',
    floorSizeM2: 30,
    area: 'sonderflaeche' as const,
    shortDescription: {
      en: "You don't need a fixed space? Take your most important business partners on an island with you.",
      de: 'Sie brauchen keinen festen Raum? Nehmen Sie Ihre wichtigsten Geschäftspartner mit auf eine Insel.',
    },
    description: {
      en: "You don't need a fixed space? You just want to take your most important business partners on an island with you? We'll raise the flag, shield you and make sure you have supplies 24/7.\n\nEquipped with a Plasma TV for presentations.",
      de: 'Sie brauchen keinen festen Raum? Sie wollen Ihre wichtigsten Geschäftspartner einfach mit auf eine Insel nehmen? Wir hissen die Flagge, schirmen Sie ab und sorgen rund um die Uhr für Nachschub.\n\nAusgestattet mit einem Plasma-TV für Präsentationen.',
    },
    capacity: {
      theater: 12,
      banquet: 8,
      uShape: 10,
      block: 10,
    },
    hasScreen: false,
    hasProjector: false,
    isDivisible: false,
    hasDaylight: false,
    displayOrder: 21,
    featured: false,
  },
]

export const lutzeHoursSeed = [
  { dayOfWeek: 'Mo-Su', opens: '10:00', closes: '01:00', segment: 'Bar' },
  { dayOfWeek: 'Mo-Su', opens: '11:30', closes: '15:00', segment: 'Kitchen' },
  { dayOfWeek: 'Mo-Su', opens: '17:00', closes: '22:30', segment: 'Kitchen' },
]

export const lutzeLocaleDe = {
  name: 'Lütze',
  tagline: 'Der Ort zum Essen, Spielen und Verweilen.',
  shortDescription:
    'Italienisches Deli-Café, Bar und Garten am Lützowplatz 17. Offen für Gäste und Berliner:innen.',
}

export const wundermartSeed = {
  name: 'Wundermart',
  slug: 'wundermart',
  venueType: 'LocalBusiness' as const,
  location: 'Lobby',
  openingHours: [{ dayOfWeek: 'Mo-Su', opens: '00:00', closes: '24:00' }],
  shortDescription:
    'Grab, Scan & Go — snacks, drinks, adapters, cables, umbrellas. Card payment.',
  isGuestFacing: true,
  isOpenToPublic: true,
  featured: false,
  displayOrder: 5,
}

export const wundermartLocaleDe = {
  name: 'Wundermart',
  shortDescription:
    'Grab, Scan & Go — Snacks, Getränke, Adapter, Ladekabel, Schirme. Zahlung per Karte.',
}

export const venuesSeed = [
  {
    name: 'Lütze',
    slug: 'lutze',
    venueType: 'Restaurant' as const,
    tagline: 'The place to eat, play, and hang all day.',
    shortDescription:
      'Italian deli café, bar, and garden at Lützowplatz 17. Open to guests and Berliners alike.',
    location: 'Ground Floor, Lützowplatz 17',
    email: 'luetze@hotel-berlin.de',
    website: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    openingHours: lutzeHoursSeed,
    spotlightLocation: 'Ground floor',
    servesCuisine: 'Italian',
    reservationUrl: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    priceRange: '€€',
    isOpenToPublic: true,
    isGuestFacing: true,
    featured: true,
    displayOrder: 1,
  },
  {
    name: 'FKKB — Freiluft Kunst Klub Berlin',
    slug: 'fkkb',
    venueType: 'ArtGallery' as const,
    tagline: 'Artists in residence. The hotel just gives it a home.',
    shortDescription:
      'Independent art gallery with artists in residence, murals on every floor, and exhibitions that change and return.',
    location: 'Hotel Berlin, Berlin — multiple floors',
    website: 'https://fkkb.de',
    instagramUrl: 'https://instagram.com/freiluftkunstklub',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 2,
  },
  {
    name: 'KTTK — Königlicher Tischtennis Klub Berlin',
    slug: 'kttk',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'Four JOOLA tables. Open to guests, open to Berliners.',
    shortDescription:
      'Table tennis club in the hotel basement. Thursday tournament nights from 19:00. No booking, no dress code. €5 entry.',
    location: 'B2 Basement',
    website: 'https://hotel-berlin.de',
    openingHours: [
      { dayOfWeek: 'Mo-Su', opens: '13:00', closes: '23:00', segment: 'Open Play' },
      {
        dayOfWeek: 'Thursday',
        opens: '19:00',
        closes: '02:00',
        isOpenEnded: true,
        segment: 'Tournament Night',
      },
    ],
    spotlightLocation: 'B2 Basement',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'Sissi Skateboard Club',
    slug: 'sissi',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'A meeting space that dances out of line.',
    shortDescription:
      'Mini-ramp built by skateboarders. Permanent home of the WALLRIDE exhibition by Jürgen Blümlein. Available as a meeting and event space.',
    location: 'Hotel Berlin, Berlin',
    website: 'https://fkkb.de/sissi-club',
    isOpenToPublic: true,
    featured: false,
    displayOrder: 4,
  },
  wundermartSeed,
  {
    name: 'Wallride',
    slug: 'wallride',
    venueType: 'LocalBusiness' as const,
    shortDescription:
      'Permanent half-pipe exhibition — Cold War Berlin skate history, curated by Jürgen Blümlein and Skateboardmuseum Berlin.',
    location: 'B2 · outside KTTK',
    spotlightLocation: 'B2 Basement',
    isGuestFacing: true,
    isOpenToPublic: true,
    featured: false,
    displayOrder: 6,
  },
  {
    name: 'Gym',
    slug: 'gym',
    venueType: 'SportsActivityLocation' as const,
    shortDescription: '24/7 gym for hotel guests.',
    location: 'In the hotel',
    openingHours: [{ dayOfWeek: 'Mo-Su', opens: '00:00', closes: '24:00' }],
    isGuestFacing: true,
    isOpenToPublic: false,
    featured: false,
    displayOrder: 7,
  },
  {
    name: 'Sauna & Sanarium',
    slug: 'sauna',
    venueType: 'LocalBusiness' as const,
    shortDescription:
      'Finnish sauna and Sanarium. 45 minutes’ notice. Hours contradict on the source site — do not pick a schedule until the hotel confirms.',
    location: 'In the hotel',
    isGuestFacing: true,
    isOpenToPublic: false,
    featured: false,
    displayOrder: 8,
  },
  {
    name: 'Bett & Bike',
    slug: 'bett-and-bike',
    venueType: 'LocalBusiness' as const,
    shortDescription: 'Bike rental for guests. Confirm current offer at reception.',
    location: 'In the hotel',
    isGuestFacing: true,
    isOpenToPublic: false,
    featured: false,
    displayOrder: 9,
  },
  {
    name: 'Business Center',
    slug: 'business-center',
    venueType: 'LocalBusiness' as const,
    shortDescription: 'Business center and on-site ATM.',
    location: 'In the hotel',
    isGuestFacing: true,
    isOpenToPublic: false,
    featured: false,
    displayOrder: 10,
  },
  {
    name: 'EV charging',
    slug: 'e-laden',
    venueType: 'LocalBusiness' as const,
    shortDescription: '8 × Type 2 charging stations on site.',
    location: 'On site',
    isGuestFacing: true,
    isOpenToPublic: true,
    featured: false,
    displayOrder: 11,
  },
]

export const hereAmenityLocalesDe: Record<
  string,
  { name: string; shortDescription: string; location: string }
> = {
  wallride: {
    name: 'Wallride',
    shortDescription:
      'Permanente Halfpipe-Ausstellung — Skate-Geschichte des Kalten Kriegs, kuratiert von Jürgen Blümlein und Skateboardmuseum Berlin.',
    location: 'B2 · vor KTTK',
  },
  gym: {
    name: 'Gym',
    shortDescription: '24/7 Fitnessraum für Hotelgäste.',
    location: 'Im Hotel',
  },
  sauna: {
    name: 'Sauna & Sanarium',
    shortDescription:
      'Finnische Sauna und Sanarium. 45 Minuten Vorlauf. Die Zeiten widersprechen sich auf der Quellseite — keine Variante wählen, bis das Hotel bestätigt.',
    location: 'Im Hotel',
  },
  'bett-and-bike': {
    name: 'Bett & Bike',
    shortDescription: 'Fahrradverleih für Gäste. Aktuelles Angebot an der Rezeption erfragen.',
    location: 'Im Hotel',
  },
  'business-center': {
    name: 'Business Center',
    shortDescription: 'Business Center und Geldautomat im Haus.',
    location: 'Im Hotel',
  },
  'e-laden': {
    name: 'E-Laden',
    shortDescription: '8 × Typ-2-Ladestationen vor Ort.',
    location: 'Vor Ort',
  },
}

export const faqsSeed = [
  // —— Prospect (homepage mini pulls category: general) ——
  {
    slug: 'check-in-time',
    question: 'What time can I check in at Hotel Berlin, Berlin?',
    answer:
      'Check-in at Hotel Berlin, Berlin is from 15:00. Early check-in from 06:00 is available for €30 if a room is ready — or book the night before for guaranteed early access.',
    questionDE: 'Wann kann ich im Hotel Berlin, Berlin einchecken?',
    answerDE:
      'Check-in im Hotel Berlin, Berlin ist ab 15:00. Früher Check-in ab 06:00 gibt es für 30 €, wenn ein Zimmer bereit ist — oder die Nacht davor buchen für garantierten frühen Zugang.',
    context: 'prospect' as const,
    category: 'general' as const,
    order: 1,
  },
  {
    slug: 'parking',
    question: 'Is there parking at Hotel Berlin, Berlin?',
    answer:
      'Yes. Hotel Berlin, Berlin has underground parking with over 200 spaces. €4 per hour, maximum €25 per day. EV charging is available nearby.',
    questionDE: 'Gibt es Parkplätze im Hotel Berlin, Berlin?',
    answerDE:
      'Ja. Das Hotel Berlin, Berlin hat eine Tiefgarage mit über 200 Plätzen. 4 € pro Stunde, maximal 25 € pro Tag. E-Ladestationen gibt es in der Nähe.',
    context: 'prospect' as const,
    category: 'general' as const,
    order: 2,
  },
  {
    slug: 'pet-policy',
    question: 'Are pets allowed at Hotel Berlin, Berlin?',
    answer:
      'Yes, pets are welcome at Hotel Berlin, Berlin. There is a charge of €30 per night. Pets are also welcome at breakfast.',
    questionDE: 'Sind Haustiere im Hotel Berlin, Berlin erlaubt?',
    answerDE:
      'Ja, Haustiere sind im Hotel Berlin, Berlin willkommen. 30 € pro Nacht. Haustiere sind auch beim Frühstück willkommen.',
    context: 'prospect' as const,
    category: 'general' as const,
    order: 3,
  },
  {
    slug: 'airport-transfer',
    question: 'How do I get to Hotel Berlin, Berlin from BER airport?',
    answer:
      'Take the RE7 or RB14 to Zoologischer Garten, then Bus 100 to Lützowplatz — right outside the hotel. Around 45–55 minutes total.',
    questionDE: 'Wie komme ich vom BER-Flughafen zum Hotel Berlin, Berlin?',
    answerDE:
      'Mit RE7 oder RB14 zum Zoologischen Garten, dann Bus 100 bis Lützowplatz — direkt vor dem Hotel. Rund 45–55 Minuten.',
    context: 'prospect' as const,
    category: 'general' as const,
    order: 4,
  },
  {
    slug: 'cancellation-flexible',
    question: 'What is the cancellation policy for a flexible rate?',
    answer:
      'Flexible rate bookings at Hotel Berlin, Berlin can be cancelled free of charge until 18:00 on the day of arrival. A late cancellation or no-show is charged at 90% of the first night.',
    questionDE: 'Wie lautet die Stornierungsbedingung beim flexiblen Tarif?',
    answerDE:
      'Flexible Buchungen im Hotel Berlin, Berlin können bis 18:00 am Anreisetag kostenfrei storniert werden. Bei später Stornierung oder No-Show werden 90 % der ersten Nacht berechnet.',
    context: 'prospect' as const,
    category: 'rooms-booking' as const,
    order: 10,
  },
  {
    slug: 'breakfast-times',
    question: 'What are the breakfast times at Hotel Berlin?',
    answer:
      'Breakfast is served daily from 06:30 to 10:00. It is a full buffet with vegan options available.',
    questionDE: 'Wann ist das Frühstück im Hotel Berlin?',
    answerDE:
      'Frühstück gibt es täglich von 06:30 bis 10:00. Volles Buffet mit veganen Optionen.',
    context: 'prospect' as const,
    category: 'dining' as const,
    order: 20,
  },
  // —— Guest ——
  {
    slug: 'guest-wifi',
    question: 'How do I connect to the hotel WiFi?',
    answer:
      'Ask at the Guest Care Center beside the lobby for the current network details. They will get you online.',
    questionDE: 'Wie verbinde ich mich mit dem WLAN?',
    answerDE:
      'Die aktuellen Netzdaten gibt es im Guest Care Center neben der Lobby. Dort wirst du online gebracht.',
    context: 'guest' as const,
    category: 'wifi-tech' as const,
    order: 1,
  },
  {
    slug: 'guest-luggage',
    question: 'Where can I store luggage before check-in or after check-out?',
    answer:
      'Luggage storage is available before check-in and after check-out. Ask at the Guest Care Center beside the lobby.',
    questionDE: 'Wo kann ich mein Gepäck vor dem Check-in oder nach dem Check-out lassen?',
    answerDE:
      'Gepäckaufbewahrung gibt es vor dem Check-in und nach dem Check-out. Frag im Guest Care Center neben der Lobby.',
    context: 'guest' as const,
    category: 'guest-services' as const,
    order: 2,
  },
  {
    slug: 'guest-checkout',
    question: 'What time is check-out?',
    answer:
      'Check-out is by 12:00. Later check-out is arranged with the lobby hosts — ask on the morning you leave.',
    questionDE: 'Wann ist der Check-out?',
    answerDE:
      'Check-out ist bis 12:00. Späterer Check-out läuft über die Lobby Hosts — am Abreisetag in der Lobby fragen.',
    context: 'guest' as const,
    category: 'guest-services' as const,
    order: 3,
  },
  {
    slug: 'guest-neighbourhood-walk',
    question: 'What is worth seeing within a short walk of the hotel?',
    answer:
      'Tiergarten, the Landwehrkanal, and Ku’damm are all within walking distance of Lützowplatz. Ask reception for a printed map, or open the neighbourhood guide in the guest hub.',
    questionDE: 'Was lohnt sich in kurzer Gehweite vom Hotel?',
    answerDE:
      'Tiergarten, Landwehrkanal und Ku’damm sind zu Fuß vom Lützowplatz erreichbar. An der Rezeption gibt es eine gedruckte Karte, oder öffne den Kiezführer im Guest Hub.',
    context: 'guest' as const,
    category: 'neighbourhood-guest' as const,
    order: 4,
  },
  {
    slug: 'guest-general-reception',
    question: 'Who do I ask if I need anything during my stay?',
    answer:
      'Reception is available 24 hours at Hotel Berlin, Berlin. For restaurant, spa, or event questions, they will point you to the right team.',
    questionDE: 'Wen frage ich, wenn ich während meines Aufenthalts etwas brauche?',
    answerDE:
      'Die Rezeption im Hotel Berlin, Berlin ist rund um die Uhr besetzt. Bei Fragen zu Restaurant, Spa oder Veranstaltungen wird man an das richtige Team verwiesen.',
    context: 'guest' as const,
    category: 'general' as const,
    order: 5,
  },
]

/** All skeleton pages — matches doc/pages/HotelBerlin_SkeletonPages_BuildBrief.md */
export const pagesSeed = [
  {
    slug: 'rooms',
    titleEN: 'Rooms & Suites',
    titleDE: 'Zimmer & Suiten',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'restaurant',
    titleEN: 'Lütze — Eat & Drink',
    titleDE: 'Lütze — Essen & Trinken',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'meetings',
    titleEN: 'Meetings & Events',
    titleDE: 'Tagungen & Veranstaltungen',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'neighbourhood',
    titleEN: 'Neighbourhood',
    titleDE: 'Nachbarschaft',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'about',
    titleEN: 'About',
    titleDE: 'Über uns',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'happenings',
    titleEN: "What's on",
    titleDE: 'Was ist los',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'people',
    titleEN: 'People',
    titleDE: 'Menschen',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'on-the-walls',
    titleEN: 'On the Walls',
    titleDE: 'On the Walls',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here',
    titleEN: 'Guest Hub',
    titleDE: 'Gästehub',
    context: 'inside' as const,
    status: 'in-progress' as const,
  },
  {
    slug: 'here/events',
    titleEN: "What's on tonight",
    titleDE: 'Was ist los',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/art',
    titleEN: 'Art programme',
    titleDE: 'Kunstprogramm',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/dining',
    titleEN: 'Dining',
    titleDE: 'Essen & Trinken',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/explore',
    titleEN: 'Explore the area',
    titleDE: 'Die Nachbarschaft',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/faq',
    titleEN: 'Guest FAQs',
    titleDE: 'Gäste-FAQ',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/getting-around',
    titleEN: 'Getting around',
    titleDE: 'So kommst du hin',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/gallery',
    titleEN: 'Gallery',
    titleDE: 'Galerie',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/wallride',
    titleEN: 'Wallride',
    titleDE: 'Wallride',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/cancellation',
    titleEN: 'Cancellation policy',
    titleDE: 'Stornierungsbedingungen',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/check-in',
    titleEN: 'Check-in & check-out',
    titleDE: 'Check-in & Check-out',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/pets',
    titleEN: 'Pet policy',
    titleDE: 'Haustierregelung',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/fees',
    titleEN: 'Parking & fees',
    titleDE: 'Parken & Gebühren',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/payment',
    titleEN: 'Payment policy',
    titleDE: 'Zahlungsbedingungen',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'accessibility',
    titleEN: 'Accessibility',
    titleDE: 'Barrierefreiheit',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'terms-conditions',
    titleEN: 'Terms & conditions',
    titleDE: 'AGB',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'privacy-policy',
    titleEN: 'Privacy policy',
    titleDE: 'Datenschutz',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'imprint',
    titleEN: 'Imprint',
    titleDE: 'Impressum',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
] as const

/** Default secondary nav — max 5, drag-reorderable in Payload */
export const defaultInsideNavSlugs: string[] = [
  'here/events',
  'here/getting-around',
  'here/explore',
  'here/gallery',
  'here/wallride',
]
