import amenityTagsSeed from './data/amenity-tags.json'

import type { AmenityTagSeed } from './types'

export const tagsSeed = [
  { name: 'Art', slug: 'art', type: 'category' as const },
  { name: 'Sport', slug: 'sport', type: 'category' as const },
  { name: 'Music', slug: 'music', type: 'category' as const },
  { name: 'Food & Drink', slug: 'food-drink', type: 'category' as const },
  { name: 'Community', slug: 'community', type: 'category' as const },
  { name: 'Neighbourhood', slug: 'neighbourhood', type: 'category' as const },
  { name: 'Culture', slug: 'culture', type: 'category' as const },
  { name: 'Screen Print', slug: 'screen-print', type: 'medium' as const },
  { name: 'Mural', slug: 'mural', type: 'medium' as const },
  { name: 'Photography', slug: 'photography', type: 'medium' as const },
  { name: 'Skateboarding', slug: 'skateboarding', type: 'theme' as const },
  { name: 'Urban Art', slug: 'urban-art', type: 'theme' as const },
  { name: 'Tiergarten', slug: 'tiergarten', type: 'neighbourhood' as const },
  { name: 'Schöneberg', slug: 'schoeneberg', type: 'neighbourhood' as const },
  ...(amenityTagsSeed as AmenityTagSeed[]),
]

export const hotelSeed = {
  name: 'Hotel Berlin, Berlin',
  legalName: 'Pandox Berlin GmbH',
  url: 'https://hotel-berlin.de',
  telephone: '+493026050',
  conferencePhone: '+4930260526 02',
  email: 'info@hotel-berlin.de',
  address: {
    streetAddress: 'Lützowplatz 17',
    addressLocality: 'Berlin',
    postalCode: '10785',
    addressCountry: 'DE',
  },
  geo: { latitude: 52.5036, longitude: 13.3522 },
  hasMap: 'https://maps.google.com/?q=52.5036,13.3522',
  directionsUrl:
    'https://www.google.com/maps/dir/?api=1&destination=52.5036,13.3522',
  mapBounds: {
    north: 52.516,
    south: 52.497,
    west: 13.34,
    east: 13.378,
  },
  checkinTime: '15:00',
  checkoutTime: '12:00',
  starRating: 4,
  priceRange: '€€',
  totalRooms: 701,
  foundingDate: '1958',
  brand: 'Radisson Individuals',
  parentOrganization: 'Pandox AB',
  wikidataId: 'Q1630833',
  sameAs: [
    { url: 'https://www.facebook.com/hotel.berlin/' },
    { url: 'https://www.instagram.com/hotel_berlin_berlin/' },
    { url: 'https://www.wikidata.org/entity/Q1630833' },
  ],
  amenityFeature: [
    { name: 'Free WiFi', value: true },
    { name: 'Underground Parking', value: true },
    { name: 'Sauna', value: true },
    { name: 'Fitness Centre', value: true },
    { name: 'Pet Friendly', value: true },
    { name: 'EV Charging Nearby', value: true },
    { name: '24/7 Reception', value: true },
    { name: 'Luggage Storage', value: true },
    { name: 'Non-Smoking Rooms', value: true },
    { name: 'Accessible Rooms Available', value: true },
  ],
  certifications: [
    { name: 'BREEAM', url: 'https://breaam.com' },
    { name: 'The Green Key', url: 'https://www.green-key.org' },
    { name: 'Cvent Top 25 Europe Independent Hotels' },
    { name: 'Sustainable Meetings Berlin Leader' },
    { name: 'Sustainable Berlin Leader' },
  ],
  openingHours: {
    reception: 'Mo-Su 00:00-24:00',
    breakfast: 'Mo-Su 06:30-10:00',
  },
}

export const meetingRoomsSeed = [
  {
    name: 'Berlin, Berlin',
    slug: 'berlin-berlin',
    floorSizeM2: 540,
    area: 'ballroom' as const,
    shortDescription:
      '540m² ballroom. The city\'s best independent meeting space — theatre for 550, reception for 1,200.',
    capacity: { classroom: 440, theatre: 550, banquet: 450, cabaret: 250, reception: 1200 },
    features: { screen: true, projector: true, divisible: true, naturalLight: false, hybridReady: true },
    displayOrder: 1,
    featured: true,
  },
  {
    name: 'Berlin 1',
    slug: 'berlin-1',
    floorSizeM2: 90,
    area: 'area-c' as const,
    shortDescription: '90m². Combinable with Berlin 2 and Berlin 3.',
    capacity: { classroom: 60, theatre: 90, banquet: 50, uShape: 32, cabaret: 45, reception: 180, block: 35 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 2,
    featured: false,
    combinableWith: ['berlin-2', 'berlin-3'],
  },
  {
    name: 'Berlin 2',
    slug: 'berlin-2',
    floorSizeM2: 90,
    area: 'area-c' as const,
    shortDescription: '90m². Combinable with Berlin 1 and Berlin 3.',
    capacity: { classroom: 60, theatre: 90, banquet: 50, uShape: 32, cabaret: 45, reception: 260, block: 35 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 3,
    featured: false,
    combinableWith: ['berlin-1', 'berlin-3'],
  },
  {
    name: 'Berlin 3',
    slug: 'berlin-3',
    floorSizeM2: 180,
    area: 'area-c' as const,
    shortDescription: '180m². Combinable with Berlin 1 and Berlin 2.',
    capacity: { classroom: 120, theatre: 180, banquet: 150, uShape: 70, cabaret: 70, reception: 260, block: 48 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 4,
    featured: true,
    combinableWith: ['berlin-1', 'berlin-2'],
  },
  {
    name: 'Berlin 4',
    slug: 'berlin-4',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 5, and Berlin 6.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 5,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-5', 'berlin-6'],
  },
  {
    name: 'Berlin 5',
    slug: 'berlin-5',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 4, and Berlin 6.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 6,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-6'],
  },
  {
    name: 'Berlin 6',
    slug: 'berlin-6',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 4, and Berlin 5.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 7,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-5'],
  },
  {
    name: 'Meeting Room A1',
    slug: 'meeting-room-a1',
    floorSizeM2: 73,
    area: 'area-a' as const,
    shortDescription: '73m². State-of-the-art technology, appealing design.',
    capacity: { classroom: 40, theatre: 60, banquet: 50, uShape: 30, cabaret: 45, reception: 90, block: 28 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 8,
    featured: true,
  },
  {
    name: 'Meeting Room A2',
    slug: 'meeting-room-a2',
    floorSizeM2: 46,
    area: 'area-a' as const,
    shortDescription: '46m². Intimate and well-equipped.',
    capacity: { classroom: 20, theatre: 30, banquet: 20, uShape: 18, reception: 40 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 9,
    featured: false,
  },
  {
    name: 'Meeting Room A3',
    slug: 'meeting-room-a3',
    floorSizeM2: 50,
    area: 'area-a' as const,
    shortDescription: '50m². Flexible layout, full AV.',
    capacity: { classroom: 24, theatre: 32, banquet: 30, uShape: 20, reception: 40 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 10,
    featured: false,
  },
  {
    name: 'Meeting Room A4',
    slug: 'meeting-room-a4',
    floorSizeM2: 72,
    area: 'area-a' as const,
    shortDescription: '72m². Mirror of A1 — same spec, same quality.',
    capacity: { classroom: 40, theatre: 60, banquet: 50, uShape: 30, cabaret: 45, reception: 80, block: 28 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 11,
    featured: false,
  },
  {
    name: 'Meeting Room B1',
    slug: 'meeting-room-b1',
    floorSizeM2: 30,
    area: 'area-b' as const,
    shortDescription: '30m². Boardroom style. Screen included. Seats 8.',
    capacity: { reception: 8, block: 8 },
    features: { screen: true, projector: false, divisible: false },
    displayOrder: 12,
    featured: false,
  },
]

export const venuesSeed = [
  {
    name: 'Lütze',
    slug: 'lutze',
    venueType: 'Restaurant' as const,
    tagline: 'The place to eat, play, and hang all day.',
    shortDescription:
      'Italian deli café, bar, and garden at Lützowplatz 17. Open to guests and Berliners alike.',
    location: 'Ground Floor, Lützowplatz 17',
    email: 'luetze@hotel-berlin.de',
    website: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    openingHours: [
      { dayOfWeek: 'Mo-Su', opens: '10:00', closes: 'open end', label: 'Bar' },
      { dayOfWeek: 'Mo-Su', opens: '11:30', closes: '15:00', label: 'Kitchen lunch' },
      { dayOfWeek: 'Mo-Su', opens: '17:00', closes: '22:30', label: 'Kitchen dinner' },
    ],
    servesCuisine: 'Italian, International',
    reservationUrl: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    priceRange: '€€',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 1,
  },
  {
    name: 'FKKB — Freiluft Kunst Klub Berlin',
    slug: 'fkkb',
    venueType: 'ArtGallery' as const,
    tagline: 'Artists in residence. The hotel just gives it a home.',
    shortDescription:
      'Independent art gallery with artists in residence, murals on every floor, and exhibitions that change and return.',
    location: 'Hotel Berlin, Berlin — multiple floors',
    website: 'https://fkkb.de',
    instagramUrl: 'https://instagram.com/freiluftkunstklub',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 2,
  },
  {
    name: 'KTTK — Königlicher Tischtennis Klub Berlin',
    slug: 'kttk',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'Four JOOLA tables. Open to guests, open to Berliners.',
    shortDescription:
      'Table tennis club in the hotel basement. Thursday tournament nights from 19:00. No booking, no dress code. €5 entry.',
    location: 'B2 Basement',
    website: 'https://hotel-berlin.de',
    openingHours: [
      { dayOfWeek: 'Thursday', opens: '19:00', closes: 'open end', label: 'Tournament Night' },
    ],
    isOpenToPublic: true,
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'Sissi Skateboard Club',
    slug: 'sissi',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'A meeting space that dances out of line.',
    shortDescription:
      'Mini-ramp built by skateboarders. Permanent home of the WALLRIDE exhibition by Jürgen Blümlein. Available as a meeting and event space.',
    location: 'Hotel Berlin, Berlin',
    website: 'https://fkkb.de/sissi-club',
    isOpenToPublic: true,
    featured: false,
    displayOrder: 4,
  },
]

export const faqsSeed = [
  {
    question: 'What time can I check in at Hotel Berlin, Berlin?',
    answer:
      'Check-in at Hotel Berlin, Berlin is from 15:00. Early check-in is available for €30 if a room is ready. If you arrive between 06:00 and 12:00, the previous night must be booked. Online check-in and self-service kiosks are available on site.',
    audience: 'both' as const,
    category: 'check-in' as const,
    priority: 1,
  },
  {
    question: 'What time is check-out at Hotel Berlin, Berlin?',
    answer:
      'Check-out at Hotel Berlin, Berlin is by 12:00 noon. Late check-out may be available on request — ask at reception on the morning of departure.',
    audience: 'guest' as const,
    category: 'check-in' as const,
    priority: 2,
  },
  {
    question: 'What is the cancellation policy for a flexible rate at Hotel Berlin?',
    answer:
      'Flexible rate bookings at Hotel Berlin, Berlin can be cancelled free of charge until 18:00 on the day of arrival. A late cancellation or no-show results in a charge of 90% of the first night.',
    audience: 'prospect' as const,
    category: 'cancellation' as const,
    priority: 3,
  },
  {
    question: 'What is the cancellation policy for an early booker rate?',
    answer:
      'For the Early Booker 10% discount rate, free cancellation applies up to 3 days before arrival — after that, 90% of the total stay is charged. For the Early Booker 15% rate, free cancellation applies up to 7 days before arrival.',
    audience: 'prospect' as const,
    category: 'cancellation' as const,
    priority: 4,
  },
  {
    question: 'Is there parking at Hotel Berlin, Berlin?',
    answer:
      'Yes. Hotel Berlin, Berlin has underground parking with over 200 spaces. The rate is €4 per hour, with a maximum of €25 per day. EV charging is available nearby.',
    audience: 'both' as const,
    category: 'parking' as const,
    priority: 5,
  },
  {
    question: 'Are pets allowed at Hotel Berlin, Berlin?',
    answer:
      'Yes, pets are welcome at Hotel Berlin, Berlin. There is a charge of €30 per night. Pets are welcome at breakfast.',
    audience: 'both' as const,
    category: 'pets' as const,
    priority: 6,
  },
  {
    question: 'How do I get to Hotel Berlin, Berlin from the airport?',
    answer:
      'From Berlin Brandenburg Airport (BER), take the RE7 or RB14 train to Zoologischer Garten, then bus 100 to Lützowplatz. The hotel is at Lützowplatz 17, 10785 Berlin.',
    audience: 'prospect' as const,
    category: 'transport' as const,
    priority: 7,
  },
  {
    question: 'What are the breakfast times at Hotel Berlin?',
    answer:
      'Breakfast is served daily from 06:30 to 10:00. It is a full buffet with vegan options available.',
    audience: 'both' as const,
    category: 'dining' as const,
    priority: 8,
  },
  {
    question: 'Is there WiFi at Hotel Berlin, Berlin?',
    answer:
      'Yes. Free WiFi is available in all rooms and throughout the hotel at Hotel Berlin, Berlin.',
    audience: 'both' as const,
    category: 'amenities' as const,
    priority: 9,
  },
  {
    question: 'Does Hotel Berlin, Berlin have a sauna or fitness centre?',
    answer: 'Yes. Hotel Berlin, Berlin has a sauna and fitness centre available to guests.',
    audience: 'both' as const,
    category: 'amenities' as const,
    priority: 10,
  },
  {
    question: 'Where can I store luggage at Hotel Berlin, Berlin?',
    answer: 'Luggage storage is available at Hotel Berlin, Berlin. Ask at reception.',
    audience: 'guest' as const,
    category: 'amenities' as const,
    priority: 11,
  },
  {
    question: 'What payment methods are accepted at Hotel Berlin?',
    answer:
      'A credit card is required at booking. Full prepayment is charged after the free cancellation window closes. Company billing can be arranged at check-in.',
    audience: 'prospect' as const,
    category: 'payment' as const,
    priority: 12,
  },
]

/** All skeleton pages — matches doc/pages/HotelBerlin_SkeletonPages_BuildBrief.md */
export const pagesSeed = [
  {
    slug: 'rooms',
    titleEN: 'Rooms & Suites',
    titleDE: 'Zimmer & Suiten',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'restaurant',
    titleEN: 'Lütze — Eat & Drink',
    titleDE: 'Lütze — Essen & Trinken',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'meetings',
    titleEN: 'Meetings & Events',
    titleDE: 'Tagungen & Veranstaltungen',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'neighbourhood',
    titleEN: 'Neighbourhood',
    titleDE: 'Nachbarschaft',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'about',
    titleEN: 'About',
    titleDE: 'Über uns',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'happenings',
    titleEN: "What's on",
    titleDE: 'Was ist los',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'people',
    titleEN: 'People',
    titleDE: 'Menschen',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'on-the-walls',
    titleEN: 'On the Walls',
    titleDE: 'On the Walls',
    context: 'outside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here',
    titleEN: 'Guest Hub',
    titleDE: 'Gästehub',
    context: 'inside' as const,
    status: 'in-progress' as const,
  },
  {
    slug: 'here/events',
    titleEN: "What's on tonight",
    titleDE: 'Was ist los',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/art',
    titleEN: 'Art programme',
    titleDE: 'Kunstprogramm',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/dining',
    titleEN: 'Dining',
    titleDE: 'Essen & Trinken',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/explore',
    titleEN: 'Explore the area',
    titleDE: 'Die Nachbarschaft',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/faq',
    titleEN: 'Guest FAQs',
    titleDE: 'Gäste-FAQ',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/getting-around',
    titleEN: 'Getting around',
    titleDE: 'So kommst du hin',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/gallery',
    titleEN: 'Gallery',
    titleDE: 'Galerie',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'here/wallride',
    titleEN: 'Wallride',
    titleDE: 'Wallride',
    context: 'inside' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/cancellation',
    titleEN: 'Cancellation policy',
    titleDE: 'Stornierungsbedingungen',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/check-in',
    titleEN: 'Check-in & check-out',
    titleDE: 'Check-in & Check-out',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/pets',
    titleEN: 'Pet policy',
    titleDE: 'Haustierregelung',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/fees',
    titleEN: 'Parking & fees',
    titleDE: 'Parken & Gebühren',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'policies/payment',
    titleEN: 'Payment policy',
    titleDE: 'Zahlungsbedingungen',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'accessibility',
    titleEN: 'Accessibility',
    titleDE: 'Barrierefreiheit',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'terms-conditions',
    titleEN: 'Terms & conditions',
    titleDE: 'AGB',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'privacy-policy',
    titleEN: 'Privacy policy',
    titleDE: 'Datenschutz',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
  {
    slug: 'imprint',
    titleEN: 'Imprint',
    titleDE: 'Impressum',
    context: 'policy' as const,
    status: 'skeleton' as const,
  },
] as const

/** Default secondary nav — max 5, drag-reorderable in Payload */
export const defaultInsideNavSlugs: string[] = [
  'here/events',
  'here/getting-around',
  'here/explore',
  'here/gallery',
  'here/wallride',
]
