export const tagsSeed = [
  { name: 'Art', slug: 'art', type: 'category' as const },
  { name: 'Sport', slug: 'sport', type: 'category' as const },
  { name: 'Music', slug: 'music', type: 'category' as const },
  { name: 'Food & Drink', slug: 'food-drink', type: 'category' as const },
  { name: 'Community', slug: 'community', type: 'category' as const },
  { name: 'Neighbourhood', slug: 'neighbourhood', type: 'category' as const },
  { name: 'Culture', slug: 'culture', type: 'category' as const },
  { name: 'Screen Print', slug: 'screen-print', type: 'medium' as const },
  { name: 'Mural', slug: 'mural', type: 'medium' as const },
  { name: 'Photography', slug: 'photography', type: 'medium' as const },
  { name: 'Skateboarding', slug: 'skateboarding', type: 'theme' as const },
  { name: 'Urban Art', slug: 'urban-art', type: 'theme' as const },
  { name: 'Free WiFi', slug: 'free-wifi', type: 'amenity' as const },
  { name: 'Air Conditioning', slug: 'air-conditioning', type: 'amenity' as const },
  { name: 'Wellness Bathroom', slug: 'wellness-bathroom', type: 'amenity' as const },
  { name: 'Balcony', slug: 'balcony', type: 'amenity' as const },
  { name: 'Tiergarten', slug: 'tiergarten', type: 'neighbourhood' as const },
  { name: 'Schöneberg', slug: 'schoeneberg', type: 'neighbourhood' as const },
]

export const hotelSeed = {
  name: 'Hotel Berlin, Berlin',
  legalName: 'Pandox Berlin GmbH',
  url: 'https://hotel-berlin.de',
  telephone: '+493026050',
  conferencePhone: '+4930260526 02',
  email: 'info@hotel-berlin.de',
  address: {
    streetAddress: 'Lützowplatz 17',
    addressLocality: 'Berlin',
    postalCode: '10785',
    addressCountry: 'DE',
  },
  geo: { latitude: 52.5034, longitude: 13.3572 },
  hasMap: 'https://maps.google.com/?q=52.5034,13.3572',
  checkinTime: '15:00',
  checkoutTime: '12:00',
  starRating: 4,
  priceRange: '€€',
  totalRooms: 701,
  foundingDate: '1958',
  brand: 'Radisson Individuals',
  parentOrganization: 'Pandox AB',
  wikidataId: 'Q1630833',
  sameAs: [
    { url: 'https://www.facebook.com/hotel.berlin/' },
    { url: 'https://www.instagram.com/hotel_berlin_berlin/' },
    { url: 'https://www.wikidata.org/entity/Q1630833' },
  ],
  amenityFeature: [
    { name: 'Free WiFi', value: true },
    { name: 'Underground Parking', value: true },
    { name: 'Sauna', value: true },
    { name: 'Fitness Centre', value: true },
    { name: 'Pet Friendly', value: true },
    { name: 'EV Charging Nearby', value: true },
    { name: '24/7 Reception', value: true },
    { name: 'Luggage Storage', value: true },
    { name: 'Non-Smoking Rooms', value: true },
    { name: 'Accessible Rooms Available', value: true },
  ],
  certifications: [
    { name: 'BREEAM', url: 'https://breaam.com' },
    { name: 'The Green Key', url: 'https://www.green-key.org' },
    { name: 'Cvent Top 25 Europe Independent Hotels' },
    { name: 'Sustainable Meetings Berlin Leader' },
    { name: 'Sustainable Berlin Leader' },
  ],
  openingHours: {
    reception: 'Mo-Su 00:00-24:00',
    breakfast: 'Mo-Su 06:30-10:00',
  },
}

export const roomsSeed = [
  {
    name: 'Individual',
    slug: 'individual',
    fromPrice: 72.25,
    currency: 'EUR',
    shortDescription: 'Double bed, free WiFi. A quiet room that does its job without fuss.',
    bedConfiguration: { type: 'queen' as const, details: '1 Queen Bed (160×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 0, maxTotal: 2 },
    featured: false,
    displayOrder: 1,
  },
  {
    name: 'Cosy Small',
    slug: 'cosy-small',
    fromPrice: 72.25,
    currency: 'EUR',
    shortDescription: 'King or queen bed with rain shower. Compact and well thought-through.',
    bedConfiguration: { type: 'king' as const, details: 'King or Queen Bed' },
    occupancy: { maxAdults: 2, maxChildren: 0, maxTotal: 2 },
    featured: false,
    displayOrder: 2,
  },
  {
    name: 'Standard',
    slug: 'standard',
    fromPrice: 72.25,
    currency: 'EUR',
    floorSizeM2: 25,
    shortDescription:
      'Part of the You, Me & Berlin series — resident stories woven into the room design.',
    bedConfiguration: { type: 'queen' as const, details: '1 Queen Bed (160×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    storyConnection: { hasStory: true, storyTeaser: 'A room with a Berlin story built in.' },
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'Superior',
    slug: 'superior',
    fromPrice: 80.75,
    currency: 'EUR',
    shortDescription: 'Casual desk, room to think. Part of the You, Me & Berlin series.',
    bedConfiguration: { type: 'queen' as const, details: '1 Queen Bed (160×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    storyConnection: { hasStory: true, storyTeaser: 'Thoughtful details, Berlin stories.' },
    featured: true,
    displayOrder: 4,
  },
  {
    name: 'Family',
    slug: 'family',
    fromPrice: 97.75,
    currency: 'EUR',
    shortDescription: 'Bunk beds for the kids, proper space for everyone. Up to 4 people.',
    bedConfiguration: { type: 'bunk' as const, details: 'Bunk beds, up to 4 people' },
    occupancy: { maxAdults: 2, maxChildren: 2, maxTotal: 4 },
    featured: false,
    displayOrder: 5,
  },
  {
    name: 'Premium Family',
    slug: 'premium-family',
    fromPrice: 92.65,
    currency: 'EUR',
    shortDescription: 'Four extra bunk beds. The room that fits the whole crew — up to 6 people.',
    bedConfiguration: { type: 'bunk' as const, details: '4 extra bunk beds, up to 6 people' },
    occupancy: { maxAdults: 2, maxChildren: 4, maxTotal: 6 },
    featured: false,
    displayOrder: 6,
  },
  {
    name: 'Premium',
    slug: 'premium',
    fromPrice: 106.25,
    currency: 'EUR',
    shortDescription: 'Spacious, wellness bathroom, king-size bed. Some rooms have a balcony.',
    bedConfiguration: { type: 'king' as const, details: '1 King Bed (180×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    featured: true,
    displayOrder: 7,
  },
  {
    name: 'Junior Suite',
    slug: 'junior-suite',
    fromPrice: 122.4,
    currency: 'EUR',
    shortDescription: 'King-size bed, proper seating area, separate toilet and bathroom.',
    bedConfiguration: { type: 'king' as const, details: '1 King Bed (180×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    featured: false,
    displayOrder: 8,
  },
  {
    name: 'Suite — One Bedroom',
    slug: 'suite-one-bedroom',
    fromPrice: 122.4,
    currency: 'EUR',
    shortDescription: 'King-size bed, seating area, separate toilet and bathroom. A suite that earns the name.',
    bedConfiguration: { type: 'king' as const, details: '1 King Bed (180×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    featured: false,
    displayOrder: 9,
  },
  {
    name: 'Corner Suite',
    slug: 'corner-suite',
    fromPrice: 173.4,
    currency: 'EUR',
    floorSizeM2: 50,
    shortDescription: 'Wellness bathroom, lounge alcove, king-size bed. Corner views, proper space.',
    bedConfiguration: { type: 'king' as const, details: '1 King Bed (180×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    featured: true,
    displayOrder: 10,
  },
  {
    name: 'Studio 45',
    slug: 'studio-45',
    fromPrice: 389.0,
    currency: 'EUR',
    floorSizeM2: 95,
    shortDescription:
      '95m². Named for Studio 54 and the Lionel Hampton legacy. The most distinctive room in the hotel.',
    bedConfiguration: { type: 'king' as const, details: '1 King Bed (180×200cm)' },
    occupancy: { maxAdults: 2, maxChildren: 1, maxTotal: 3 },
    featured: true,
    displayOrder: 11,
  },
]

export const meetingRoomsSeed = [
  {
    name: 'Berlin, Berlin',
    slug: 'berlin-berlin',
    floorSizeM2: 540,
    area: 'ballroom' as const,
    shortDescription:
      '540m² ballroom. The city\'s best independent meeting space — theatre for 550, reception for 1,200.',
    capacity: { classroom: 440, theatre: 550, banquet: 450, cabaret: 250, reception: 1200 },
    features: { screen: true, projector: true, divisible: true, naturalLight: false, hybridReady: true },
    displayOrder: 1,
    featured: true,
  },
  {
    name: 'Berlin 1',
    slug: 'berlin-1',
    floorSizeM2: 90,
    area: 'area-c' as const,
    shortDescription: '90m². Combinable with Berlin 2 and Berlin 3.',
    capacity: { classroom: 60, theatre: 90, banquet: 50, uShape: 32, cabaret: 45, reception: 180, block: 35 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 2,
    featured: false,
    combinableWith: ['berlin-2', 'berlin-3'],
  },
  {
    name: 'Berlin 2',
    slug: 'berlin-2',
    floorSizeM2: 90,
    area: 'area-c' as const,
    shortDescription: '90m². Combinable with Berlin 1 and Berlin 3.',
    capacity: { classroom: 60, theatre: 90, banquet: 50, uShape: 32, cabaret: 45, reception: 260, block: 35 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 3,
    featured: false,
    combinableWith: ['berlin-1', 'berlin-3'],
  },
  {
    name: 'Berlin 3',
    slug: 'berlin-3',
    floorSizeM2: 180,
    area: 'area-c' as const,
    shortDescription: '180m². Combinable with Berlin 1 and Berlin 2.',
    capacity: { classroom: 120, theatre: 180, banquet: 150, uShape: 70, cabaret: 70, reception: 260, block: 48 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 4,
    featured: true,
    combinableWith: ['berlin-1', 'berlin-2'],
  },
  {
    name: 'Berlin 4',
    slug: 'berlin-4',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 5, and Berlin 6.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 5,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-5', 'berlin-6'],
  },
  {
    name: 'Berlin 5',
    slug: 'berlin-5',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 4, and Berlin 6.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 6,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-6'],
  },
  {
    name: 'Berlin 6',
    slug: 'berlin-6',
    floorSizeM2: 60,
    area: 'area-c' as const,
    shortDescription: '60m². Combinable with Berlin 3, Berlin 4, and Berlin 5.',
    capacity: { classroom: 30, theatre: 60, banquet: 30, uShape: 25, cabaret: 27, reception: 80, block: 25 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 7,
    featured: false,
    combinableWith: ['berlin-3', 'berlin-4', 'berlin-5'],
  },
  {
    name: 'Meeting Room A1',
    slug: 'meeting-room-a1',
    floorSizeM2: 73,
    area: 'area-a' as const,
    shortDescription: '73m². State-of-the-art technology, appealing design.',
    capacity: { classroom: 40, theatre: 60, banquet: 50, uShape: 30, cabaret: 45, reception: 90, block: 28 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 8,
    featured: true,
  },
  {
    name: 'Meeting Room A2',
    slug: 'meeting-room-a2',
    floorSizeM2: 46,
    area: 'area-a' as const,
    shortDescription: '46m². Intimate and well-equipped.',
    capacity: { classroom: 20, theatre: 30, banquet: 20, uShape: 18, reception: 40 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 9,
    featured: false,
  },
  {
    name: 'Meeting Room A3',
    slug: 'meeting-room-a3',
    floorSizeM2: 50,
    area: 'area-a' as const,
    shortDescription: '50m². Flexible layout, full AV.',
    capacity: { classroom: 24, theatre: 32, banquet: 30, uShape: 20, reception: 40 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 10,
    featured: false,
  },
  {
    name: 'Meeting Room A4',
    slug: 'meeting-room-a4',
    floorSizeM2: 72,
    area: 'area-a' as const,
    shortDescription: '72m². Mirror of A1 — same spec, same quality.',
    capacity: { classroom: 40, theatre: 60, banquet: 50, uShape: 30, cabaret: 45, reception: 80, block: 28 },
    features: { screen: true, projector: true, divisible: false },
    displayOrder: 11,
    featured: false,
  },
  {
    name: 'Meeting Room B1',
    slug: 'meeting-room-b1',
    floorSizeM2: 30,
    area: 'area-b' as const,
    shortDescription: '30m². Boardroom style. Screen included. Seats 8.',
    capacity: { reception: 8, block: 8 },
    features: { screen: true, projector: false, divisible: false },
    displayOrder: 12,
    featured: false,
  },
]

export const venuesSeed = [
  {
    name: 'Lütze',
    slug: 'lutze',
    venueType: 'Restaurant' as const,
    tagline: 'The place to eat, play, and hang all day.',
    shortDescription:
      'Italian deli café, bar, and garden at Lützowplatz 17. Open to guests and Berliners alike.',
    location: 'Ground Floor, Lützowplatz 17',
    email: 'luetze@hotel-berlin.de',
    website: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    openingHours: [
      { dayOfWeek: 'Mo-Su', opens: '10:00', closes: 'open end', label: 'Bar' },
      { dayOfWeek: 'Mo-Su', opens: '11:30', closes: '15:00', label: 'Kitchen lunch' },
      { dayOfWeek: 'Mo-Su', opens: '17:00', closes: '22:30', label: 'Kitchen dinner' },
    ],
    servesCuisine: 'Italian, International',
    reservationUrl: 'https://hotel-berlin.de/en/eat-drink/luetze-bar-berlin',
    priceRange: '€€',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 1,
  },
  {
    name: 'FKKB — Freiluft Kunst Klub Berlin',
    slug: 'fkkb',
    venueType: 'ArtGallery' as const,
    tagline: 'Artists in residence. The hotel just gives it a home.',
    shortDescription:
      'Independent art gallery with artists in residence, murals on every floor, and exhibitions that change and return.',
    location: 'Hotel Berlin, Berlin — multiple floors',
    website: 'https://fkkb.de',
    instagramUrl: 'https://instagram.com/freiluftkunstklub',
    isOpenToPublic: true,
    featured: true,
    displayOrder: 2,
  },
  {
    name: 'KTTK — Königlicher Tischtennis Klub Berlin',
    slug: 'kttk',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'Four JOOLA tables. Open to guests, open to Berliners.',
    shortDescription:
      'Table tennis club in the hotel basement. Thursday tournament nights from 19:00. No booking, no dress code. €5 entry.',
    location: 'B2 Basement',
    website: 'https://hotel-berlin.de',
    openingHours: [
      { dayOfWeek: 'Thursday', opens: '19:00', closes: 'open end', label: 'Tournament Night' },
    ],
    isOpenToPublic: true,
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'Sissi Skateboard Club',
    slug: 'sissi',
    venueType: 'SportsActivityLocation' as const,
    tagline: 'A meeting space that dances out of line.',
    shortDescription:
      'Mini-ramp built by skateboarders. Permanent home of the WALLRIDE exhibition by Jürgen Blümlein. Available as a meeting and event space.',
    location: 'Hotel Berlin, Berlin',
    website: 'https://fkkb.de/sissi-club',
    isOpenToPublic: true,
    featured: false,
    displayOrder: 4,
  },
]

export const faqsSeed = [
  {
    question: 'What time can I check in at Hotel Berlin, Berlin?',
    answer:
      'Check-in at Hotel Berlin, Berlin is from 15:00. Early check-in is available for €30 if a room is ready. If you arrive between 06:00 and 12:00, the previous night must be booked. Online check-in and self-service kiosks are available on site.',
    audience: 'both' as const,
    category: 'check-in' as const,
    priority: 1,
  },
  {
    question: 'What time is check-out at Hotel Berlin, Berlin?',
    answer:
      'Check-out at Hotel Berlin, Berlin is by 12:00 noon. Late check-out may be available on request — ask at reception on the morning of departure.',
    audience: 'guest' as const,
    category: 'check-in' as const,
    priority: 2,
  },
  {
    question: 'What is the cancellation policy for a flexible rate at Hotel Berlin?',
    answer:
      'Flexible rate bookings at Hotel Berlin, Berlin can be cancelled free of charge until 18:00 on the day of arrival. A late cancellation or no-show results in a charge of 90% of the first night.',
    audience: 'prospect' as const,
    category: 'cancellation' as const,
    priority: 3,
  },
  {
    question: 'What is the cancellation policy for an early booker rate?',
    answer:
      'For the Early Booker 10% discount rate, free cancellation applies up to 3 days before arrival — after that, 90% of the total stay is charged. For the Early Booker 15% rate, free cancellation applies up to 7 days before arrival.',
    audience: 'prospect' as const,
    category: 'cancellation' as const,
    priority: 4,
  },
  {
    question: 'Is there parking at Hotel Berlin, Berlin?',
    answer:
      'Yes. Hotel Berlin, Berlin has underground parking with over 200 spaces. The rate is €4 per hour, with a maximum of €25 per day. EV charging is available nearby.',
    audience: 'both' as const,
    category: 'parking' as const,
    priority: 5,
  },
  {
    question: 'Are pets allowed at Hotel Berlin, Berlin?',
    answer:
      'Yes, pets are welcome at Hotel Berlin, Berlin. There is a charge of €30 per night. Pets are welcome at breakfast.',
    audience: 'both' as const,
    category: 'pets' as const,
    priority: 6,
  },
  {
    question: 'How do I get to Hotel Berlin, Berlin from the airport?',
    answer:
      'From Berlin Brandenburg Airport (BER), take the RE7 or RB14 train to Zoologischer Garten, then bus 100 to Lützowplatz. The hotel is at Lützowplatz 17, 10785 Berlin.',
    audience: 'prospect' as const,
    category: 'transport' as const,
    priority: 7,
  },
  {
    question: 'What are the breakfast times at Hotel Berlin?',
    answer:
      'Breakfast is served daily from 06:30 to 10:00. It is a full buffet with vegan options available.',
    audience: 'both' as const,
    category: 'dining' as const,
    priority: 8,
  },
  {
    question: 'Is there WiFi at Hotel Berlin, Berlin?',
    answer:
      'Yes. Free WiFi is available in all rooms and throughout the hotel at Hotel Berlin, Berlin.',
    audience: 'both' as const,
    category: 'amenities' as const,
    priority: 9,
  },
  {
    question: 'Does Hotel Berlin, Berlin have a sauna or fitness centre?',
    answer: 'Yes. Hotel Berlin, Berlin has a sauna and fitness centre available to guests.',
    audience: 'both' as const,
    category: 'amenities' as const,
    priority: 10,
  },
  {
    question: 'Where can I store luggage at Hotel Berlin, Berlin?',
    answer: 'Luggage storage is available at Hotel Berlin, Berlin. Ask at reception.',
    audience: 'guest' as const,
    category: 'amenities' as const,
    priority: 11,
  },
  {
    question: 'What payment methods are accepted at Hotel Berlin?',
    answer:
      'A credit card is required at booking. Full prepayment is charged after the free cancellation window closes. Company billing can be arranged at check-in.',
    audience: 'prospect' as const,
    category: 'payment' as const,
    priority: 12,
  },
]
